spring:
  datasource:
    url: jdbc:mysql://database-1.ce83fb4wyqzu.us-west-1.rds.amazonaws.com:3306/hrishislife
    username: admin
    password: Ebcm107hirshi592^
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8

  web:
    resources:
      cache:
        cachecontrol:
          no-cache: true

  security:
    oauth2:
      client:
        registration:
            google:
                client-id: 888343728100-1jig4iuojon9nnskef51ia2fpvvhfbtk.apps.googleusercontent.com
                client-secret: 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
                scope:
                - email
                - profile

server:
  port: 8080
  ssl:
    enabled: false
    key-store-type: JKS
    key-store: ~/cert.jks
    key-store-password: Ebcm107hirshi592^

chrome-driver:
  use-path: false
  path: /Users/hrishikesh/Downloads/chromedriver

github:
  webhooks:
    secret: oSMh6lohVAauLup7FX2We1irVUsI3JZg
